# Python version required to run the project.
python: "3.11.5"
# Dependencies required to build packages. This field is optional.
build_dependencies:
  - pip
  - setuptools
  - wheel==0.37.1
# Dependencies required to run the project.
dependencies:
  - tensorflow==2.12.0
  - torch==2.1.0
  - transformers==4.33.1
  - datasets==2.14.1
  - tqdm==4.66.1
  - ray[tune]==2.7.0
  - mlflow==2.7.1
  - torchvision==0.16.0
  - typing-extensions==4.5.0
